# numpy

In [1]:
# IT is a  foundation stack for all other python libraries
# It is used for array computations
# mainly used for image processing  applications
# numpy arrys are very faster than python list
# array - is a collection of homogenous items

In [2]:
import numpy as np

# numpy array creation

In [3]:
L=[23,45,67,89,79]
type(L)

list

In [4]:
a=np.array(L)
a

array([23, 45, 67, 89, 79])

In [5]:
print(a)
type(a)

[23 45 67 89 79]


numpy.ndarray

In [6]:
b=np.array([23,79,85,47])
b

array([23, 79, 85, 47])

In [7]:
#memory  address of an array object
a.data

In [8]:
# convert an array into floating point
b=a.astype(float)
b.dtype#checks data type

dtype('float64')

In [9]:
#generate evenly spaced numbers from 0 to 10 with step size1
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#generate number number betwen 100 to 10 with step size -10
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [12]:
#shape of an array
a=np.array ([23,2,12,3,4,5,52,78])
a.shape

(8,)

In [13]:
a.size

8

In [14]:
b=np.array([[2,3,4,5],[3,4,5,6],[7,8,9,4]])
b.shape

(3, 4)

In [15]:
b.size

12

In [16]:
a.ndim #no of dimentions

1

In [17]:
#two dimentional array
b=np.array([[2,4,25],[4,5,6],[8,9,3]])
b

array([[ 2,  4, 25],
       [ 4,  5,  6],
       [ 8,  9,  3]])

In [18]:
b.ndim

2

In [19]:
b.dtype

dtype('int32')

In [20]:
a

array([23,  2, 12,  3,  4,  5, 52, 78])

In [21]:
#bytes occupied by an each item in an array
a.itemsize

4

In [22]:
a.nbytes#total no of bytes occupied by an array

32

In [23]:
len(a)

8

In [24]:
len(b)

3

In [25]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
#genate ones array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#diagonal martix
np.diag([2,4,6])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [31]:
#report
#generate an array of 5 elements (all 10s)
np.repeat(10,5)

In [32]:
#repeat each element in array for thrice
a=np.array([10,20,30])
np.repeat(a,3)

In [138]:
#generate an array of all even numbers in a range 2,20
a=np.arange(2,20)
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [139]:
b=np.arange(2,20)
b[b%2==1]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [140]:
a=np.array([23,54,89,78])
a.min()

23

In [141]:
a.max()

89

In [142]:
a.argmin()#returns index of min

0

In [143]:
a.argmax()

2

In [144]:
#generate linearly spaced 5 items between 10 to 20
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [145]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [146]:
#create an array of random numbers
np.random.random(5)#return 5 random no from 0 to 1

array([0.07728957, 0.4444695 , 0.47280797, 0.048522  , 0.16332445])

In [147]:
np.random.random(10)

array([0.11595071, 0.62739168, 0.85618205, 0.65010242, 0.99072168,
       0.47035075, 0.61829448, 0.28266721, 0.97600332, 0.673068  ])

In [148]:
np.random.randint(10,20,5)

array([14, 16, 14, 19, 11])

In [149]:
np.random.randint(0,500,10)

array([  6, 364,  42,  11, 232, 136,  49,  77, 379, 203])

In [150]:
print(np.random.seed(45))#seed number gives same output random numbers
np.random.randint(0,100,5)#if we exectute this again we get same same output

None


array([75, 30,  3, 32, 95])

In [151]:
#cummulative sum
a

array([23, 54, 89, 78])

In [152]:
a.cumsum()

array([ 23,  77, 166, 244], dtype=int32)

In [153]:
b=np.array([[3,4,5],[4,5,6],[5,6,7]])
b

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [154]:
b.sum()

45

In [155]:
b[1]

array([4, 5, 6])

In [156]:
b[0]

array([3, 4, 5])

In [157]:
b.sum(axis=0)#colums axis=0
#rows axis=1

array([12, 15, 18])

In [158]:
b.sum(axis=1)

array([12, 15, 18])

In [159]:
b[0:2,0:2]

array([[3, 4],
       [4, 5]])

In [160]:
c=np.array([[9,8,2,1,],[3,4,8,6],[2,2,6,7],[4,2,1,8]])
c

array([[9, 8, 2, 1],
       [3, 4, 8, 6],
       [2, 2, 6, 7],
       [4, 2, 1, 8]])

In [161]:
c[:,0:2]

array([[9, 8],
       [3, 4],
       [2, 2],
       [4, 2]])

In [162]:
d=np.array([23.56,67.12,56.78,90.7,23.4])
d

array([23.56, 67.12, 56.78, 90.7 , 23.4 ])

In [163]:
np.floor(d)

array([23., 67., 56., 90., 23.])

In [164]:
#mean of array

In [165]:
a

array([23, 54, 89, 78])

In [166]:
a.mean()#returns mean of an array

61.0

In [167]:
np.median(a)

66.0

In [168]:
f=np.arange(0,20)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [169]:
f.reshape([5,4])#reshaping an array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [170]:
a=np.array([23,45,6,78,89,90])

In [171]:
a[1]

45

In [172]:
b

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [173]:
b[1][1]

5

In [174]:
a

array([23, 45,  6, 78, 89, 90])

In [175]:
a[::-1]

array([90, 89, 78,  6, 45, 23])

In [176]:
c=np.array(['s','a','m','q'])
c

array(['s', 'a', 'm', 'q'], dtype='<U1')

In [177]:
np.amin(b,axis=1)

array([3, 4, 5])

In [178]:
b

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [179]:
import numpy as np
np.amin(b,axis=0)#colums axis=0
#rows axis=1

array([3, 4, 5])

In [180]:
a=np.arange(1,20)

In [181]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [182]:
res=np.where(a%2==0,0,a)
res

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19])

In [183]:
b= np.array([10,30,20,30,10,30,10,10,10,50])
b

array([10, 30, 20, 30, 10, 30, 10, 10, 10, 50])

In [184]:
res=np.where(b==10,99,b)
res

array([99, 30, 20, 30, 99, 30, 99, 99, 99, 50])

In [185]:
c=np.arange(0,100,10)
c

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [186]:
#replce the values at index location 0,3,5 with 33,44,55

In [187]:
np.put(c,[0,3,5],[33,44,55])

In [188]:
c

array([33, 10, 20, 44, 40, 55, 60, 70, 80, 90])

In [189]:
#missing values in an array

In [190]:
a=np.array([10,np.nan,20,30,np.nan,60,80,np.nan,90,100])
a

array([ 10.,  nan,  20.,  30.,  nan,  60.,  80.,  nan,  90., 100.])

In [191]:
#search for missing values and return a boolean array

In [192]:
np.isnan(a)

array([False,  True, False, False,  True, False, False,  True, False,
       False])

In [193]:
np.where(np.isnan(a))

(array([1, 4, 7], dtype=int64),)

In [194]:
a[np.isnan(a)]=100
a

array([ 10., 100.,  20.,  30., 100.,  60.,  80., 100.,  90., 100.])

In [195]:
np.isnan(a).any()

False

In [196]:
d=np.array([12,np.nan])
d

array([12., nan])

In [197]:
np.isnan(d).any()

True

In [198]:
A=np.array([[1,2,np.nan,5],[34,67,np.nan,23],[12,36,90,np.nan],[np.nan,66,np.nan,34]])
A

array([[ 1.,  2., nan,  5.],
       [34., 67., nan, 23.],
       [12., 36., 90., nan],
       [nan, 66., nan, 34.]])

In [199]:
np.isnan(A)

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

In [200]:
np.where(np.isnan(A))

(array([0, 1, 2, 3, 3], dtype=int64), array([2, 2, 3, 0, 2], dtype=int64))

In [201]:
#Stack array horizontally

In [202]:
a=np.array([23,45,67,12,6])
b=np.array([34,1,2,34,5])

In [203]:
import numpy as np
np.hstack([a,b])

array([23, 45, 67, 12,  6, 34,  1,  2, 34,  5])

In [204]:
np.hstack([b,a])

array([34,  1,  2, 34,  5, 23, 45, 67, 12,  6])

In [205]:
#stack array vertically

In [206]:
np.vstack([a,b])

array([[23, 45, 67, 12,  6],
       [34,  1,  2, 34,  5]])

In [207]:
np.vstack([b,a])

array([[34,  1,  2, 34,  5],
       [23, 45, 67, 12,  6]])

In [208]:
#find common items btwen two arrays

In [209]:
a=np.array([10,20,30,40,50,60])
b=np.array([12,20,33,40,55,60])
a,b

(array([10, 20, 30, 40, 50, 60]), array([12, 20, 33, 40, 55, 60]))

In [210]:
np.intersect1d(a,b)

array([20, 40, 60])

In [211]:
#remove common elements
np.setdiff1d(a,b)

array([10, 30, 50])

In [212]:
np.setdiff1d(b,a)

array([12, 33, 55])

In [213]:
#process elements on a condition

In [214]:
a=np.array([1,2,3,4,8])
b=np.array([10,2,30,60,8])
a,b

(array([1, 2, 3, 4, 8]), array([10,  2, 30, 60,  8]))

In [215]:
np.where(a==b)

(array([1, 4], dtype=int64),)

In [216]:
#return an array where condition is satisfied
a[np.where(a==b)]

array([2, 8])

In [217]:
#return all numbers between 20&35
a=np.arange(0,60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [218]:
a[np.where((a>20) & (a<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [219]:
a[np.where(((a>20) & (a<35)) |(a%10==0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [220]:
#return all numbers between 20 & 35 using np.logical_and()
a[np.where(np.logical_and(a>20,a<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [221]:
#isin
a=np.array([10,20,30,40,50,60,70])
a

array([10, 20, 30, 40, 50, 60, 70])

In [222]:
np.isin(a,[70,100])

array([False, False, False, False, False, False,  True])

In [223]:
np.isin(a,[50])

array([False, False, False, False,  True, False, False])

In [224]:
#display index when match is occur
np.where(np.isin(a,[10,70]))

(array([0, 6], dtype=int64),)

In [225]:
#print matching valuesa
a[np.where(np.isin(a,[10,34]))]


array([10])

In [226]:
a=np.arange(10,70,10)
#reverse the array
a[::-1]

array([60, 50, 40, 30, 20, 10])

In [227]:
np.flip(a)

array([60, 50, 40, 30, 20, 10])

In [228]:
a=np.array([[2,3,4],[5,6,7],[8,9,10]])
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [229]:
#reverse the row position
a[::-1]

array([[ 8,  9, 10],
       [ 5,  6,  7],
       [ 2,  3,  4]])

In [230]:
#reverse the col position
a[:,::-1]

array([[ 4,  3,  2],
       [ 7,  6,  5],
       [10,  9,  8]])

In [231]:
#reverse both col and row position
a[::-1,::-1]

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [232]:
#sorting array

In [233]:
a=np.array([34,67,12,10,89,36])
a

array([34, 67, 12, 10, 89, 36])

In [234]:
np.sort(a)

array([10, 12, 34, 36, 67, 89])

In [235]:
a=np.array([[3,2,8,1],[70,50,10,67],[45,25,75,15]])
a

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [236]:
#sort along rows
np.sort(a)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [237]:
#sort along rows
np.sort(a,axis=1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [238]:
#sort along col
np.sort(a,axis=0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [239]:
np.transpose(a)

array([[ 3, 70, 45],
       [ 2, 50, 25],
       [ 8, 10, 75],
       [ 1, 67, 15]])

In [240]:
a=np.array([[1,2,3],[2,4,5]])
b=np.array([[4,5,6],[6,8,9]])

In [241]:
np.hstack([a,b])

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 5, 6, 8, 9]])

In [242]:
np.vstack([a,b])

array([[1, 2, 3],
       [2, 4, 5],
       [4, 5, 6],
       [6, 8, 9]])